### ISSUE TITLE
language code issue:  checkout form not shown in opencart 

### ISSUE THREAD

**Issue by MuhamedAuda** [iyzico/iyzipay-opencart#10]
Hello, when opencart site work with Arabic language Iyzipay checkout form not appear at checkout page .
It work fine with English language

**Comment by MuhamedAuda** [comment]
I have fixed it and updated code ..thanks

**Comment by zeynelagca** [comment]
> 
> 
> I have fixed it and updated code ..thanks

Hi Muhammed , 
We  have been facing the same issue .Can you  give me  the detail how you fixed it ?
