### ISSUE TITLE
PHP Notice: Undefined index: in /public_html/system/library/cart/currency.php on line 25,27,30

### ISSUE THREAD

**Issue by ssdwho** [iyzico/iyzipay-opencart#13]
Merhaba, ödeme gerçekleştikten sonra gelen sayfada bu hata yer alıyor. Ödeme gerçekleşiyor ancak bu hatayı gidermenin yolunu bulamadım. 
https://prnt.sc/r1thi3

**Comment by bayrakkemre** [comment]
Merhabalar,
Yaşadığınız sorun için üzgünüz. Konu ile ilgili entregrasyon@iyzico.com adresi üzerinden iletişime geçebilirseniz yardımcı olmaktan isteriz.
Anlayışınız için teşekkürler.
