### ISSUE TITLE
Odeme ekrani acilir acilmaz popup tetikleniyor

### ISSUE THREAD

**Issue by caglayanadiguzel** [iyzico/iyzipay-opencart#14]
Selamlar,

Iyzico entegrasyonunun son kismina gelmis bulunuyoruz. Tek sikintimiz popup opsiyonunun odeme sayfasini acar acmaz direk karsimiza gelmesi. Normalde bunun, "Siparisi Dogrula" butonuna tikladiktan sonra cikmasini bekleniyor. Bu dedigim oluyor ama basta da soyledigim gibi ilk acilista direk karsisina gelmesi kullanim acisindan cok kafa karistirici. 

Journal Quick Checkout kullaniyoruz. Sizce bunu nasil engelleyebiliriz?

websitesi:www.tuckcoffee.shop
Opencart Version: 3.0.3.6
PHP 7.3.26
Journal: Version 3.1.7

Saygilar,
Caglayan Adiguzel

**Comment by sozgat** [comment]
Merhaba @caglayanadiguzel ,

Ben iyzico geliştirme ekibinden, Said. Detaylı inceleme ve bilgi almak için entegrasyon@iyzico.com adresi ile iletişime geçebilir misiniz? 

İyi günler dilerim.

**Comment by sozgat** [comment]
Merhaba @caglayanadiguzel,

Opencart 3.x-2.0v ile Journal 3 Tema üzerindeki hata giderilmiştir. Modülünüzü son versiyona güncelleyip, iyzico modül ayarlarından form ayarını One Page olarak işaretlediğinizde form tetiklenmeyecektir.

Değerli geri bildiriminiz için teşekkürler. İyi günler dilerim.
