### ISSUE TITLE
Kart Numara Alanı Tasarım Hatası

### ISSUE THREAD

**Issue by uslualper** [iyzico/iyzipay-opencart#18]
Merhaba,

Opencart eklentinizi kurduk ve responsive görünümü seçtik. Kart numarası girme alanında ufak bir tasarımsal kayma meydana geldi.  Sorunun kaynağı bizim düzenlediğimiz opencart tasarımlarından kaynaklanıyor diye düşündük fakat sorun ancak  ".css-1u40dsv-InputHolder" class'ına  float:left özelliğini ekleyince düzeldi. 

![Screenshot_3](https://user-images.githubusercontent.com/23556436/115007995-4510de00-9eb3-11eb-8756-cd26016ca493.png)

**Comment by sozgat** [comment]
Merhaba @uslualper ,

Ben said, iyzico geliştirici ekibindeyim.  Opencart altyapısındaki , iyziconun kullandığı temel fonksiyonları değiştiren herhangi bir modül veya tema iyzico modülü ile uyumlu çalışmayarak bu hataya sebebiyet vermiş olabilir. 

Biz geliştirdiğimiz modülleri yalın kurulumlarda ve en sık kullanılan tema/modüllerle test ederek sorunsuz çalıştığını gördükten sonra siz değerli müşterilerimize sunmaktayız. 

Başka sorunlar yaşadığınız takdirde entregrasyon@iyzico.com adresi üzerinden iletişime geçebilirseniz yardımcı olmaktan memnuniyet duyarız.

İyi günler dileriz.
